"""Simple file‑based storage for events and detections.

The storage layer records events emitted by sensors and detections
generated by the analysis engine.  Each event is stored as a line of
JSON in a log file.  This format is easy to process later with tools like
`jq` or `pandas`.

The storage directory is defined in `config.LOG_DIR`.  Two files are
maintained:

* `events.log` – one JSON object per line representing a sensor event.
* `detections.log` – one JSON object per line representing an anomaly.

Each record contains a timestamp in ISO‑8601 format.  Use
`get_recent_events` to read the most recent entries.
"""
import json
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime

import config
from utils.debug_log import debug_logger


class Storage:
    def __init__(self):
        # Ensure the log directory exists
        config.ensure_log_dir()
        self.events_file = config.LOG_DIR / "events.log"
        self.detections_file = config.LOG_DIR / "detections.log"

    def _write_record(self, file_path: Path, record: Dict[str, any]):
        """Append a JSON record to the specified file."""
        with file_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(record) + "\n")

    def log_event(self, sensor: str, payload: Dict[str, any]):
        """Record a sensor event.

        :param sensor: Name of the sensor producing the event.
        :param payload: Arbitrary data collected by the sensor.
        """
        record = {
            "timestamp": datetime.utcnow().isoformat(),
            "sensor": sensor,
            "data": payload,
        }
        self._write_record(self.events_file, record)
        debug_logger.info("Event logged", {"sensor": sensor})

    def log_detection(self, rule: str, description: str, details: Dict[str, any]):
        """Record a detection event.

        :param rule: Name of the rule that triggered.
        :param description: Human readable description of the anomaly.
        :param details: Additional contextual information.
        """
        record = {
            "timestamp": datetime.utcnow().isoformat(),
            "rule": rule,
            "description": description,
            "details": details,
        }
        self._write_record(self.detections_file, record)
        debug_logger.detection(rule, description, details)

    def get_recent_events(
        self, count: int = 20, sensor: Optional[str] = None
    ) -> List[Dict[str, any]]:
        """Return the most recent events.

        :param count: Maximum number of events to return.
        :param sensor: Optional sensor name to filter by.
        :return: A list of event records ordered from newest to oldest.
        """
        events = []
        try:
            with self.events_file.open("r", encoding="utf-8") as f:
                for line in f:
                    try:
                        event = json.loads(line)
                        if sensor and event.get("sensor") != sensor:
                            continue
                        events.append(event)
                    except json.JSONDecodeError:
                        continue
        except FileNotFoundError:
            return []
        # Return the last `count` events in reverse chronological order
        return list(reversed(events[-count:]))

    def get_recent_detections(self, count: int = 20) -> List[Dict[str, any]]:
        """Return the most recent detection events."""
        detections = []
        try:
            with self.detections_file.open("r", encoding="utf-8") as f:
                for line in f:
                    try:
                        detection = json.loads(line)
                        detections.append(detection)
                    except json.JSONDecodeError:
                        continue
        except FileNotFoundError:
            return []
        return list(reversed(detections[-count:]))
